<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php
$_product              = $block->getProduct();
$_wishlistSubmitParams = $this->helper('Magento\Wishlist\Helper\Data')->getAddParams($_product);
$compareHelper         = $this->helper('Magento\Catalog\Helper\Product\Compare');
$_config               = $this->helper('Sm\Market\Helper\Data');
?>

<div class="product-addto-links" data-role="add-to-links">
    <?= $block->getChildHtml() ?>
</div>


<script type="text/x-magento-init">
    {
        "body": {
            "addToWishlist": <?php /* @escapeNotVerified */
    echo $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($block->getWishlistOptions()) ?>
        }
    }


</script>
