<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php 
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');//get current product
    $product_id = $product->getId();
    //echo $product->getName();
    $_product = $objectManager->create('Magento\Catalog\Model\Product')->load($product_id);
    $specialprice = $_product->getSpecialPrice();
    $specialtodate = $_product->getSpecialToDate();
?>
<?php
    if (!empty($specialprice) && !empty($specialtodate)) {
    //$specialToDate = $_product->getSpecialToDate();
    ?>
    <div class="deals-countdown" data-timer="<?php echo date("Y/m/d H:i:s", strtotime($specialtodate)); ?>">
        <div class="deals-time time-day">
			<div class="num-time"></div>
		   	<div class="title-time"></div>
    	</div>
	   <div class="deals-time time-hours">
	        <div class="num-time"></div>
	        <div class="title-time"></div>
	    </div>
	    <div class="deals-time time-mins">
	        <div class="num-time"></div>
	        <div class="title-time"></div>
	    </div>
	    <div class="deals-time time-secs">
	        <div class="num-time"></div>
	        <div class="title-time"></div>
	    </div>
	</div>
<?php } ?>



<script type="text/javascript">
    require([
        'jquery'
    ], function ($) {

    function CountDown(date, id) {
        dateNow = new Date();
        amount = date.getTime() - dateNow.getTime();
        delete dateNow;
        if (amount < 0) {
            id.html("Now!");
        } else {
                days = 0;
                hours = 0;
                mins = 0;
                secs = 0;
                out = "";
                amount = Math.floor(amount / 1000);
                days = Math.floor(amount / 86400);
                amount = amount % 86400;
                hours = Math.floor(amount / 3600);
                amount = amount % 3600;
                mins = Math.floor(amount / 60);
                amount = amount % 60;
                secs = Math.floor(amount);
                    $(".time-day .num-time", id).text(days);
                    $(".time-day .title-time", id).text(((days <= 1) ? "<?php echo __('Day')?>" : "<?php echo __('Days')?>"));
                    $(".time-hours .num-time", id).text(hours);
                    $(".time-hours .title-time", id).text(((hours <= 1) ? "<?php echo __('Hour')?>" : "<?php echo __('Hours')?>"));
                    $(".time-mins .num-time", id).text(mins);
                    $(".time-mins .title-time", id).text(((mins <= 1) ? "<?php echo __('Min')?>" : "<?php echo __('Mins')?>"));
                    $(".time-secs .num-time", id).text(secs);
                    $(".time-secs .title-time", id).text(((secs <= 1) ? "<?php echo __('Sec')?>" : "<?php echo __('Secs')?>"));
            		setTimeout(function () {
                        CountDown(date, id)
                    }, 1000);
            }
           }

            $(".deals-countdown").each(function () {
                var timer = $(this).data('timer');
                var data = new Date(timer);
                CountDown(data, $(this));
            });
        });
</script>


<style type="text/css">
   .catalog-product-view .deals-countdown{
    	text-align: center;
    	width: inherit;
    }
</style>