<?php
$helper = $this->helper('Magepow\InfiniteScroll\Helper\Data');
$isEnabled      = $helper->getConfigModule('general/enabled');
$delay          = $helper->getConfigModule('general/delay');
$content        = $helper->getConfigModule('general/content');
$pagination     = $helper->getConfigModule('general/pagination');
$next           = $helper->getConfigModule('general/next');
$item           = $helper->getConfigModule('general/item');
$loadingText    = $helper->getConfigModule('general/loading_text');
$doneText       = $helper->getConfigModule('general/done_text');
$loadMore       = $helper->getConfigModule('general/load_more');
$loadMoreText   = $helper->getConfigModule('general/load_more_text');
$loadingImage   = $helper->getConfigModule('general/loading_image');
$imgPath        = 'magepow/infinitescroll/'.$loadingImage;
if ($loadingImage) {
    $loadingImage = $block->getMedia($imgPath);
}else{
    $loadingImage = $this->getViewFileUrl('images/loader-1.gif');
}
?>
<script type="text/javascript">
    require(['jquery', 'magepow/infinitescroll'], function ($) {
        "use strict";
        $(document).ready(function () {
            $('body').addClass('infinitescroll');
            var ias = $.ias({
                container: "<?php echo $content;?>",
                item: "<?php echo $item;?>",
                pagination: "<?php echo $pagination;?>",
                next: "<?php echo $next;?>",
                delay: "<?php echo $delay;?>",
            });

            window.ias = $.ias();
            window.ias.extension(new IASSpinnerExtension({
                src: "<?php echo $loadingImage; ?>",
                html: '<div class="iass-spinner"><img src="{src}"/><span><?php echo $loadingText; ?></span></div>'
            }));

            window.ias.extension(new IASNoneLeftExtension({
                text: "<?php echo $doneText;?>",
                html: '<div class="ias-noneleft">{text}</div>'
            }));
           window.ias.extension(new IASTriggerExtension({
                text:"<?php echo $loadMoreText ?>",
                html:'<div class="ias-trigger ias-trigger-next"><button class="load-more"><?php echo $loadMoreText ?></button></div>',
                textPrev:"<?php echo $loadMoreText ?>",
                htmlPrev:'<div class="ias-trigger ias-trigger-prev"><button class="load-more"><?php echo $loadMoreText ?></button></div>',
                offset:"<?php echo $loadMore ?>",
            }));
            window.ias.on('rendered', function(items){
                $('body').trigger('contentUpdated');
                $( "form[data-role='tocart-form']" ).catalogAddToCart();
            });
            window.ias.on('rendered', function(items) {
                $(".item.product.product-item").find('.deals-countdown').each(function (event) {
                    var timer = $(this).data('timer');
                    var data = new Date(timer);
                    CountDown1(data, $(this));
                    function CountDown1(date, id) {
                        let dateNow = new Date();
                       let amount = date.getTime() - dateNow.getTime();
                        // delete dateNow;
                        if (amount < 0) {
                            id.html("Now!");
                        } else {
                           let days = 0;
                           let hours = 0;
                           let mins = 0;
                           let secs = 0;
                           let out = "";
                            amount = Math.floor(amount / 1000);
                            days = Math.floor(amount / 86400);
                            amount = amount % 86400;
                            hours = Math.floor(amount / 3600);
                            amount = amount % 3600;
                            mins = Math.floor(amount / 60);
                            amount = amount % 60;
                            secs = Math.floor(amount);
                            $(".time-day .num-time", id).text(days);
                            $(".time-day .title-time", id).text(((days <= 1) ? "<?php echo __('Day')?>//" : "<?php echo __('Days')?>//"));
                            $(".time-hours .num-time", id).text(hours);
                            $(".time-hours .title-time", id).text(((hours <= 1) ? "<?php echo __('Hour')?>" : "<?php echo __('Hours')?>"));
                            $(".time-mins .num-time", id).text(mins);
                            $(".time-mins .title-time", id).text(((mins <= 1) ? "<?php echo __('Min')?>" : "<?php echo __('Mins')?>"));
                            $(".time-secs .num-time", id).text(secs);
                            $(".time-secs .title-time", id).text(((secs <= 1) ? "<?php echo __('Sec')?>" : "<?php echo __('Secs')?>"));
                            setTimeout(function () {
                                CountDown1(date, id)
                            }, 1000);
                        }
                    }
                });
            });

        });
    });
</script>
