<?php
$collection = $block->_getProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$proIdsArr=[];
?>
<div class="wkmp-event-form-container">
    <form action="<?= /* noEscape */ $block->getUrl('marketplaceeventmanager/upcoming/events'); ?>" class="wkmp-event-form">
        <input type="text" name='q' value="<?= $block->getRequest()->getParam('q'); ?>" placeholder="Search by Name"/>
        <button><?= __('Submit'); ?></button>
        <a href="<?= /* noEscape */ $block->getUrl('marketplaceeventmanager/upcoming/events'); ?>"><?= __('Reset'); ?></a>
    </form>
</div>
<div class="wk_mp_design mp_event_list" style="padding-top: 10px;">
        <?php if (empty($collection->getData())) : ?>
        <p class="note-msg"><?= /* noEscape */ __('There are no products matching in the selection.') ?></p>
        <?php else : ?>
        <div class="category-products">
            <?= /* noEscape */ $block->getToolbarHtml() ?>
            <div style="clear:both">
            <?php // List mode ?>
            <?php $_iterator = 0; ?>
            <ol class="products wrapper list products-list" id="products-list">
            <?php foreach ($collection->getData() as $_product) :
                $_product = $block->getProductModel($_product['entity_id']);
                $eventData = $block->getProductById($_product->getEntityId());
                $proIdsArr[] = $_product->getId();
                ?>

                <li class="item<?php if (++$_iterator == count($collection)) {  echo " last"; } ?>">
                    <?php // Product Image ?>
                    <a href="<?= /* noEscape */ $_product->getProductUrl() ?>" title="<?= /* noEscape */ $block->stripTags($block->getImageLabel($_product, 'category_page_grid'), null, true) ?>" class="product-image">

                        <img src ="<?= /* noEscape */ $block->getProductImage($_product); ?>">
                    </a>

                    <?php // Product description ?>
                    <div class="product-shop">
                        <div class="f-fix">

                                <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                                <div class="product-primary">
                                <h2 class="product-name"><a href="<?= /* noEscape */ $_product->getProductUrl() ?>" title="<?= /* noEscape */ $_productNameStripped; ?>"><?= /* noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name'); ?></a></h2>
                                </div>
                                <?php if ($_product->getRatingSummary()) : ?>
                                    <?= /* noEscape */ $block->getReviewsSummaryHtml($_product) ?>
                                <?php endif; ?>

                                <div class="product-secondary">
                                <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                                </div>
                                <div class="product-secondary">
                                <?php if ($_product->getIsSalable()) : ?>
                                    <a href="<?= /* noEscape */ $block->getAddToCartUrl($_product) ?>"><button type="button" title="<?= /* noEscape */ __('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?= /* noEscape */ $block->getAddToCartUrl($_product) ?>')"><span><span><?= /* noEscape */ __('Book Ticket') ?></span></span></button></a>
                                <?php else : ?>
                                    <p class="action availability "><span><?= /* noEscape */ __('Out of stock') ?></span></p>
                                <?php endif; ?>

                                <div class="add-to-links">
                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()) : ?>
                                            <a href="#"
                                                    class="action towishlist"
                                                    title="<?= /* noEscape */ $block->escapeHtml(__('Add to Wish List')); ?>"
                                                    aria-label="<?= /* noEscape */ $block->escapeHtml(__('Add to Wish List')); ?>"
                                                    data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
                                                    data-action="add-to-wishlist"
                                                    role="button">
                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                                </a><br/>
                                    <?php endif; ?>
                                    <?php
                                            $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                    ?>
                                            <a href="#"
                                                class="action tocompare"
                                                title="<?= /* noEscape */ $block->escapeHtml(__('Add to Compare')); ?>"
                                                aria-label="<?= /* noEscape */ $block->escapeHtml(__('Add to Compare')); ?>"
                                                data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
                                                role="button">
                                                <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                                            </a>
                                </div>
                            </div>
                            <div class="desc std">
                                <?= /* noEscape */ $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                <a href="<?= /* noEscape */ $_product->getProductUrl() ?>" title="<?= /* noEscape */ $_productNameStripped ?>" class="link-learn"><?= /* noEscape */ __('View More') ?></a>
                                <?php $eventvenue =  $_product->getEventVenue();
                                if (!empty($eventvenue)) {
                                    ?>
                                <p>
                                    <a href="https://maps.google.com/?q=<?= /* noEscape */ urlencode($eventvenue); ?>" target="__blank"><?= /* noEscape */ __('View Location'); ?></a>
                                </p>
                                <?php }
                                if ($eventData->getEventStartDate()) {
                                    ?>
                                    <P>
                                        <h4><?= /* noEscape */ __('Event Start Time:'); ?></h4>
                                        <span>
                                            <?= /* noEscape */ date('g:iA \o\n l jS F Y', strtotime($block->getLocaleTime($eventData->getEventStartDate()))); ?>
                                        </span>
                                    </P>
                                <?php } if ($eventData->getEventEndDate()) { ?>
                                    <P>
                                        <h4><?= /* noEscape */ __('Event End Time:');?></h4>
                                        <span>
                                            <?= /* noEscape */ date('g:iA \o\n l jS F Y', strtotime($block->getLocaleTime($eventData->getEventEndDate()))); ?>
                                        </span>
                                    </P>
                                <?php } ?>
                                <?php $blockName = "wk_mp_event_manager_".$_product->getName()."_".$_product->getEntityId();  ?>
                                <?= /* noEscape */ $this->getLayout()
                                        ->createBlock(
                                            "Webkul\MarketplaceEventManager\Block\Product\View\Attributes",
                                            $blockName,
                                            ['data' =>['product_id' => $_product->getEntityId()]]
                                        )
                                        ->setData('area', 'frontend')
                                        ->setTemplate("Magento_Catalog::product/view/attributes.phtml")
                                        ->toHtml();
                                ?>
                            </div>
                        </div>
                    </div>
                </li>
            <?php endforeach; ?>
            </ol>
            <?= /* noEscape */ $block->getToolbarHtml() ?>
        </div>
        <?php endif; ?>
    </div>
</div>
<script type="text/javascript">
    require([
        "jquery"
    ], function ($) {
        $("body #sorter option[value='position']").remove();
        <?php
        if (empty($block->getRequest()->getParams())) {
            ?>
        var checkUpcoming = "<?= $block->getUrl('marketplaceeventmanager/upcoming/check')?>";
        var proIds = '<?= json_encode($proIdsArr)?>';
        $.ajax({
            type: "POST",
            url: checkUpcoming,
            data: {'data':proIds},
            dataType: "json",
            cache: false,
            success: function(response)
            {
                if (response.success && !response.match) {
                    // location.reload();
                }
            },
        })
            <?php
        }?>
    });
</script>
