<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_SellerStorePickup
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

$_helper = $this->helper('Webkul\Marketplace\Helper\Data');
$dataHelper = $this->helper('Webkul\MarketplaceEventManager\Helper\Data');
$isPartner= $_helper->isSeller();
$magentoCurrentUrl = $block->getCurrentUrl();
$allow_pro_type=$_helper->getAllowedProductType();
$isSellerGroup = $_helper->isSellerGroupModuleInstalled();
if ($dataHelper->isEventManagerEnable() && $isPartner) {
    ?>
<style type="text/css">
    @media only screen and (max-width: 767px){

        .block-collapsible-nav.wk-mp-main{
            top: 20px;
        }
    }
</style>
<li class="level-0 <?= /* noEscape */ strpos($magentoCurrentUrl, 'marketplaceeventmanager/event/add')? "current active":"";?>">
    <a href="#" onclick="return false;" class="">
        <span><?= /* noEscape */ __('Coupon Management')?></span>
    </a>
    <div class="wk-mp-submenu">
        <strong class="wk-mp-submenu-title"><?= /* noEscape */ __('Coupon Management')?></strong>
        <a href="#" class="action-close _close" data-role="wk-mp-close-submenu"></a>
        <ul>
            <li data-ui-id="menu-webkul-marketplace-menu" class="item-menu  parent  level-1">
                <strong class="wk-mp-submenu-group-title">
                    <span><?= /* noEscape */ __('Menu')?></span>
                </strong>
                <div class="wk-mp-submenu">
                    <ul>
                        <?php if (($isSellerGroup && $_helper->isAllowedAction('marketplaceeventmanager/event/add')) || !$isSellerGroup) { ?>
                            <li class="level-2">
                                <a href="<?= /* noEscape */ $block->getUrl('marketplaceeventmanager/event/add', ['_secure' => $this->getRequest()->isSecure()]); ?>">
                                    <span><?= /* noEscape */ __('Add Coupon Ticket') ?></span>
                                </a>
                            </li>
                        <?php } ?>
                        <?php if (($isSellerGroup && $_helper->isAllowedAction('marketplaceeventmanager/event/eventlist')) || !$isSellerGroup) { ?>
                            <li class="level-2">
                                <a href="<?= /* noEscape */ $block->getUrl('marketplaceeventmanager/event/eventlist', ['_secure' => $this->getRequest()->isSecure()]); ?>">
                                    <span><?= /* noEscape */ __('My Coupons List') ?></span>
                                </a>
                            </li>
                        <?php } ?>
                    </ul>
                </div>
            </li>
        </ul>
    </div>
</li>
<?php } ?>