<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_MarketplaceEventManager
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

/** @var $block \Webkul\Marketplace\Block\Product\Productlist */

$helper = $this->helper('Webkul\Marketplace\Helper\Data');

$paramData = $this->getRequest()->getParams();
$filter = '';
$filterStatus = '';
$filterDateFrom = '';
$filterDateTo = '';
if (isset($paramData['s'])) {
    $filter = $paramData['s'] != '' ? $paramData['s'] : '';
}
if (isset($paramData['status'])) {
    $filterStatus = $paramData['status'] != '' ? $paramData['status'] : '';
}
if (isset($paramData['from_date'])) {
    $filterDateFrom = $paramData['from_date'] != '' ? $paramData['from_date'] : '';
}
if (isset($paramData['to_date'])) {
    $filterDateTo = $paramData['to_date'] != '' ? $paramData['to_date'] : '';
}

$_products_coll = $block->getAllProducts();

?>    
<div class="wk-mp-design">
    <fieldset class="fieldset info wk-mp-fieldset">
        <legend class="legend">
            <span><?= /* noEscape */ __('Coupons List') ?></span>
        </legend>
        <div class="grid">
            <div class="hor-scroll">
                <form action="<?= /* noEscape */ $block->getUrl('marketplaceeventmanager/event/eventlist', ['_secure' => $this->getRequest()->isSecure()])?>" method="get" id="form-productlist-filter"  name="formProductlistFilter" data-mage-init='{"validation":{}}'>
                    <div class="table-wrapper">
                        <table cellspacing="0" class="data table border wk-mp-list-table">
                            <thead>
                                <tr id="wk-mp-tr-heading">
                                    <th><span><?= /* noEscape */ __('Coupon Name') ?></span></th>
                                    <th><span><?= /* noEscape */ __('Date') ?></span></th>
                                    <th><span><?= /* noEscape */ __('Coupon Status') ?></span></th>
                                    <th><span>&nbsp;</span></th>
                                </tr>
                            </thead>
                            <tbody class="wk-mp-body">
                                <tr>
                                    <td data-th="<?= /* noEscape */ __('Coupon Name') ?>" scope="col" class="col">
                                        <input type="text" class="input-text" name="s" placeholder='<?= /* noEscape */ __('Search by product name') ?>' value="<?= /* noEscape */ $filter?>"/>
                                    </td>
                                    <td data-th="<?= /* noEscape */ __('Date') ?>" scope="col" class="col">
                                        <span class="wk-mp-td-span">
                                            <?= /* noEscape */ __('From: ') ?>
                                            <input name="from_date" id="special-from-date" class="input-text" value="<?= /* noEscape */ $filterDateFrom?>" />
                                        </span>                                
                                        <span class="wk-mp-td-span">
                                            <?= /* noEscape */ __('To: ') ?>
                                            <input name="to_date" id="special-to-date" class="input-text" value="<?= /* noEscape */ $filterDateTo?>" />
                                        </span>
                                    </td>
                                    <td data-th="<?= /* noEscape */ __('Coupon Status') ?>" class="col" scope="col">
                                        <select name="status" class="input-text">
                                            <option value=""><?= /* noEscape */ __('All') ?></option>
                                            <option value="1" <?php if ($filterStatus == 1) { echo 'selected="selected"'; }?>>
                                                <?= /* noEscape */ __('Approved') ?>
                                            </option>
                                            <option value="2" <?php if ($filterStatus == 2) { echo 'selected="selected"'; }?>>
                                                <?= /* noEscape */ __('Unapproved') ?>
                                            </option>
                                        </select>
                                    </td>
                                    <td data-th="<?= /* noEscape */ __('Action') ?>" scope="col" class="col">
                                        <button class="button" title="Save" type="submit">
                                            <span><span><span><?= /* noEscape */ __('Submit') ?></span></span></span>
                                        </button>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </form>
                <?php if ($_products_coll && count($_products_coll)) : ?>
                    <form action="<?= /* noEscape */ $block->getUrl('marketplaceeventmanager/event/massDelete', ['_secure' => $this->getRequest()->isSecure()]) ?>" method="post" id="form-productlist-massdelete" name="formProductlistMassdelete" data-mage-init='{"validation":{}}'>
                        <?= /* noEscape */ $block->getBlockHtml('formkey')?>
                        <button class="button" title="<?= /* noEscape */ __('Delete Products') ?>" type="submit" style="padding: 5px 5px 5px 0;"  id="mass-delete-butn">
                            <span><span><?= /* noEscape */ __('Delete Products') ?></span></span>
                        </button>
                        <div class="table-wrapper">
                            <table cellspacing="0" class="data table border wk-mp-list-table wk-mp-list-container-table">
                                <thead>
                                    <tr class="wk-content">
                                        <th class="wk-check-first-td">
                                            <span>
                                                <input type="checkbox" name="mpselecctall" value="all" id="mpselecctall"/>
                                            </span>
                                        </th>
                                        <th class="wk-first-td">
                                            <span class="label name">
                                                <?= /* noEscape */ __('Coupon')?>
                                            </span>
                                        </th>
                                        <th>
                                            <span class="label pro-status">
                                                <?= /* noEscape */ __('Type')?>
                                            </span>
                                        </th>
                                        <th>
                                            <span class="label pro-status">
                                                <?= /* noEscape */ __('Status')?>
                                            </span>
                                        </th>
                                        <th class="wk-list-th-display">
                                            <span class="label qty">
                                                <?= /* noEscape */ __('Qty. Confirmed')?>
                                            </span>
                                        </th>
                                        <th class="wk-list-th-display">
                                            <span class="label qty">
                                                <?= /* noEscape */ __('Qty. Pending')?>
                                            </span>
                                        </th>    
                                        <th class="wk-list-th-display">
                                            <span class="label qty">
                                                <?= /* noEscape */ __('Qty. Sold')?>
                                            </span>
                                        </th>
                                        <th class="wk-list-th-display1">
                                            <span class="label">
                                                <?= /* noEscape */ __('Earned Amount')?>
                                            </span>
                                        </th>
                                        <th>
                                            <span class="label">
                                                <?= /* noEscape */ __('Action')?>
                                            </span>
                                        </th>
                                        <th>
                                            <span class="label">
                                                <?= /* noEscape */ __('Send Reminder')?>
                                            </span>
                                        </th>                    
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php
                                    $i = 0;
                                    foreach ($block->getAllProducts() as $products) {
                                        $product = $block->getProductData($products->getMageproductId());
                                        $i++;
                                        $image_url = $block->imageHelperObj()->init($product, 'product_page_image_small')
                                                    ->setImageFile($product->getImage())
                                                    ->getUrl();
                                        $salesdetail=$block->getSalesdetail($products->getMageproductId());
                                        ?>
                                        <tr class="wk-row-view <?= /* noEscape */ $class = ($i == count($block->getAllProducts()))? 'wk-last_tr':''?>">
                                            <td data-th="<?= /* noEscape */ __('Select')?>" scope="col" class="col wk-check-first-td">
                                                <span>
                                                    <input type="checkbox" name="product_mass_delete[]" class="mpcheckbox" value="<?= /* noEscape */ $products->getMageproductId(); ?>"/>
                                                </span>
                                            </td>
                                            <td data-th="<?= /* noEscape */ __('Coupon')?>" scope="col" class="col wk-first_td">
                                                <input type="hidden" class="hidden-id" value="<?= /* noEscape */ $products->getMageproductId(); ?>" />
                                                <div class="label name" title="<?= /* noEscape */ $product->getName(); ?>">
                                                    <div class="wk-pro-divide1">
                                                        <img src="<?= /* noEscape */ $image_url?>" class="image" />
                                                    </div>
                                                    <div class="wk-pro-divide2">
                                                        <div style="width:100%;">
                                                            <?php if ($product->getStatus()==1 && $product->getVisibility()!=1) { ?>
                                                                <a href="<?= /* noEscape */ $product->getProductUrl()?>" target="blank">
                                                            <?php }?>
                                                                <?= /* noEscape */ $product->getName();?>
                                                            <?php if ($product->getStatus()==1 && $product->getVisibility()!=1) { ?>
                                                                </a>
                                                            <?php }?>
                                                        </div>
                                                        <div style="width:100%;float:left;">
                                                            <?php
                                                            if ($product->getPrice()*1) {
                                                                echo $block->getFormatedPrice($product->getPrice(), $helper->getCurrencySymbol());
                                                            } else {
                                                                echo $helper->getCurrencySymbol().'0.00';
                                                            }
                                                            ?>
                                                        </div>
                                                    </div>
                                                </div>
                                            </td>
                                            <td data-th="<?= /* noEscape */ __('Type')?>" scope="col" class="col">        
                                                <span class="label pro-status">
                                                    <?= /* noEscape */ $product->getTypeId()?>
                                                </span>
                                            </td>
                                            <?php
                                            if ($product->getStatus()==2) {    ?>
                                                <td data-th="<?= /* noEscape */ __('Status')?>" scope="col" class="col">        
                                                    <span class="label pro-status">
                                                        <?= /* noEscape */ __('Pending')?>
                                                    </span>
                                                </td>
                                                <td data-th="<?= /* noEscape */ __('Qty. Confirmed')?>" scope="col" class="col wk-list-th-display">
                                                    <span class="label qty">
                                                        <?= /* noEscape */ __('Pending')?>
                                                    </span>
                                                </td>
                                                <td data-th="<?= /* noEscape */ __('Qty. Pending')?>" scope="col" class="col wk-list-th-display">
                                                    <span class="label qty">
                                                        <?= /* noEscape */ __('Pending')?>
                                                    </span>    
                                                </td>
                                                <td data-th="<?= /* noEscape */ __('Qty. Sold')?>" scope="col" class="col wk-list-th-display">
                                                    <span class="label qty">
                                                        <?= /* noEscape */ __('Pending')?>
                                                    </span>    
                                                </td>
                                                <td data-th="<?= /* noEscape */ __('Earned Amount')?>" scope="col" class="col wk-list-th-display1">
                                                    <span class="label qty">
                                                        <?= /* noEscape */ __('Pending')?>
                                                    </span>    
                                                </td>                                    
                                            <?php } else { ?>
                                                <td data-th="<?= /* noEscape */ __('Status')?>" scope="col" class="col">        
                                                    <span class="label pro-status">
                                                        <?= /* noEscape */ __('Approved')?>
                                                    </span>
                                                </td>
                                                <td data-th="<?= /* noEscape */ __('Qty. Confirmed')?>" scope="col" class="col wk-list-th-display">
                                                    <span class="label qty">
                                                        <?= /* noEscape */ $salesdetail['quantitysoldconfirmed']; ?>
                                                    </span>
                                                </td>
                                                <td data-th="<?= /* noEscape */ __('Qty. Pending')?>" scope="col" class="col wk-list-th-display">
                                                    <span class="label qty">
                                                        <?= /* noEscape */ $salesdetail['quantitysoldpending']; ?>
                                                    </span>    
                                                </td>
                                                <td data-th="<?= /* noEscape */ __('Qty. Sold')?>" scope="col" class="col wk-list-th-display1">
                                                    <span class="label qty">
                                                        <a href="<?= /* noEscape */ $block->getUrl('marketplace/order/salesdetail/', ['id'=>$product->getId(), '_secure' => $this->getRequest()->isSecure()]); ?>"><?= /* noEscape */ $salesdetail['quantitysold']; ?></a>
                                                    </span>    
                                                </td>
                                                <td data-th="<?= /* noEscape */ __('Earned Amount')?>" scope="col" class="col wk-list-th-display">
                                                    <span class="label price">
                                                        <?= /* noEscape */ $block->getFormatedPrice($salesdetail['amountearned'], $helper->getCurrencySymbol()); ?>
                                                    </span>    
                                                </td>
                                                <?php
                                            }?>
                                            <td data-th="<?= /* noEscape */ __('Action')?>" scope="col" class="col">
                                                <span class="label wk-action">
                                                    <img src="<?= /* noEscape */ $this->getViewFileUrl('Webkul_Marketplace::images/icon-edit.png'); ?>" data-url="<?= /* noEscape */ $block->getUrl('marketplaceeventmanager/event/edit', ['id'=>$product->getId(), '_secure' => $this->getRequest()->isSecure()])?>" alt="<?= /* noEscape */ __('Edit')?>" title="<?= /* noEscape */ __('Edit')?>" class="mp-edit"/>
                                                    <img src="<?= /* noEscape */ $this->getViewFileUrl('Webkul_Marketplace::images/icon-trash.png'); ?>" alt="<?= /* noEscape */ __('Delete')?>" title="<?= /* noEscape */ __('Delete')?>" class="mp-delete" data-url="<?= /* noEscape */ $block->getUrl('marketplaceeventmanager/event/delete/', ['id'=>$product->getId(), '_secure' => $this->getRequest()->isSecure()]) ?>"/>
                                                </span>    
                                            </td>
                                            <td data-th="<?= /* noEscape */ __('Send Reminder')?>" scope="col" class="col">
                                                <a href="<?= /* noEscape */ $block->getUrl('marketplaceeventmanager/event/reminder', ['pid'=>$product->getId(), '_secure' => $this->getRequest()->isSecure()])?>"><?= /* noEscape */ __('Send Reminder');?></a>
                                            </td>                    
                                        </tr>
                                        <?php
                                    }?>
                                </tbody>
                            </table>
                        </div>
                    </form>                        
                <?php else : ?>
                    <div class="wk-emptymsg">
                        <?= /* noEscape */ __('No EVENT Available') ?>
                    </div>
                <?php endif ?>                    
            </div>
        </div>
        <?php if ($block->getPagerHtml()) : ?>
            <div class="order-products-toolbar toolbar bottom"><?= /* noEscape */ $block->getPagerHtml(); ?></div>
        <?php endif ?>    
    </fieldset>    
    <div class="buttons-set">
        <p class="back-link">
            <a href="javascript:;" onclick="javascript: window.history.back();" class="left">&laquo; <?= /* noEscape */ __('Back') ?></a>
        </p>
    </div>
</div>    
<script type="text/x-magento-init">
    {
        "body": {
            "Webkul_MarketplaceEventManager/js/sellerProductListjs": {}
        }
    }
</script>