<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/**
 * Category layered navigation
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation
 */
?>

<?php if ($block->canShowBlock()): ?>
    <div class="block filter" id="layered-filter-block"
         data-mage-init='{"collapsible":{"openedState": "active", "collapsible": true, "active": false, "collateral": { "openedState": "filter-active", "element": "body" } }}'>
        <?php $filtered = count($block->getLayer()->getState()->getFilters()) ?>
        <div class="block-title filter-title" data-count="<?php /* @escapeNotVerified */
        echo $filtered; ?>">
            <strong data-role="title"><?php /* @escapeNotVerified */
                echo __('Filter Products By') ?></strong>

            <div class="close-filter">
                <a id="close-btn"><span><?php echo __('Close') ?></span></a>
            </div>
        </div>
        <div class="block-content filter-content">
            <?php echo $block->getChildHtml('state') ?>

            <?php if ($block->getLayer()->getState()->getFilters()): ?>
                <div class="block-actions filter-actions">
                    <a href="<?php /* @escapeNotVerified */
                    echo $block->getClearUrl() ?>"
                       class="action clear filter-clear"><span><?php /* @escapeNotVerified */
                            echo __('Clear All') ?></span></a>
                </div>
            <?php endif; ?>
            <?php $wrapOptions = false; ?>
            <?php foreach ($block->getFilters() as $filter): ?>
        <?php if ($filter->getItemsCount()): ?>

        <?php if (!$wrapOptions): ?>
            <strong role="heading" aria-level="2" class="block-subtitle filter-subtitle"><?php /* @escapeNotVerified */
                echo __('Shopping Options') ?></strong>
            <div class="filter-options" id="narrow-by-list" data-role="content"
                 data-mage-init='{"accordion":{"openedState": "active", "collapsible": true, "active": false, "multipleCollapsible": false}}'>
                <?php $wrapOptions = true;
                endif; ?>
                <div data-role="collapsible" class="filter-options-item">
                    <div data-role="title" class="filter-options-title"><?php /* @escapeNotVerified */
                        echo __($filter->getName()) ?><span class="cust_span">SHOW ALL</span>
                    </div>
                    <div data-role="content" class="filter-options-content"><?php /* @escapeNotVerified */
                        echo $block->getChildBlock('renderer')->render($filter); ?></div>
                </div>
                <?php endif; ?>
                <?php endforeach; ?>
                <?php if ($wrapOptions): ?>
            </div>
        <?php else: ?>
            <script>
                require([
                    'jquery'
                ], function ($) {
                    $('#layered-filter-block').addClass('filter-no-options');
                });
            </script>
            <?php endif; ?>
        </div>
    </div>

    <div class="filter-overlay"></div>
<?php endif; ?>

<style type="text/css">
    span.cust_span {
        float: right;
        cursor: pointer;
        transition: transform .2s;

    }
    span.cust_span:hover {
        transform: scale(1.2);
    }
</style>
<script type="text/javascript">
    require(['jquery'], function ($) {

        $(".cust_span").eq(0).on('click', function (e) {
            e.preventDefault();

                        $('.filter-options-content ol').find('li.level-2').slideToggle(500);

            $('.cust_span').bind('click');

            if ($('.cust_span').eq(0).text() == "SHOW ALL") {
                $('.cust_span').eq(0).text("HIDE");
            } else {
                $('.cust_span').eq(0).text("SHOW ALL");
            }
        });
    });
</script>
