<?php
        $pid = $this->getRequest()->getParam('pid');
        $oid = $this->getRequest()->getParam('oid');
        $helper = $this->helper('Webkul\MarketplaceEventManager\Helper\Data');
        $realOrderId = $block->getRealOrderIdVal();
        $productadata = $block->getTicketDetails();
if (!empty($productadata) && $productadata) {
    $product = $block->getProductDetails($productadata->getProductId(), $productadata);
    $optionid = 0;
    $ticketData = $productadata['product_options'];
    $optionid = 0;
    $optiontpe = '';
    foreach ($ticketData as $tds) {
        foreach ($tds as $td) {
            if (isset($td['option_id']) && isset($td['value'])) {
                    $optionid = $td['option_id'];
                     $optiontpe = $td['value'];
            }
        }
    }
            $qrprefix = $product->getEventTicketPrefix();
    if (!$qrprefix) {
        $qrprefix = $helper->getGlobalEventPrefix();
    }
            $qrprefix = strtoupper($qrprefix);
            $collection  = $block->getTicketDetailsCollection($productadata->getOrderId(), $productadata->getId(), $optionid);
    if ($collection->getSize()) {
        ?>
         <div class="wk-mp-design" id="wk-bodymain">
        <fieldset class="fieldset info wk-mp-fieldset">
            <legend class="legend">
                <span><?= /* noEscape */ __('Your Coupon Details') ?></span>
                <a target="blank" href="<?= /* noEscape */ $this->getUrl('marketplaceeventmanager/customer/printorder', ['oid'=>$oid,'pid'=>$pid]); ?>">
                    <button class="button wk-mp-btn" title="<?= /* noEscape */ __('Print') ?>" type="submit" id="save-btn">
                    <span><span><?= /* noEscape */ __('Print') ?></span></span>
                </button>
                </a>
            </legend>
        </fieldset>
        <div class="event-ticket-view">
            <table>
                <tr>
                     <td><?= /* noEscape */ __('9YDA VOUCHER QR CODE'); ?></td>
                     <td><p>
                 <?php
                    $qrimage = '';
                    foreach ($collection as $col) {
                        $qrimage = $helper->getQrImageUrl($col->getQrcode());
                    }

                    ?>
                          <img src="<?= /* noEscape */ $qrimage; ?>" />
                    </p></td>
                </tr>
                
                    <tr>
                        <td><?= /* noEscape */ __('Coupon Code'); ?></td>
                        <td><p>
                            <?= /* noEscape */ $qrprefix.$col->getQrcode(); ?>
                        </p></td>
                    </tr>
                    <tr>
                        <td><?= /* noEscape */ __('Coupon Quantity'); ?></td>
                        <td><p>
                            <?= /* noEscape */ $col->getOptionQty(); ?>
                        </p></td>
                    </tr>
                    <tr>
                        <td><?= /* noEscape */ __('Coupon Status'); ?></td>
                        <td><p>
                            <?php
                            if ($col->getStatus() == 1) {
                                echo __("Valid Coupon");
                            } else {
                                echo __("Used Coupon");
                            }
                            ?></p>
                        </p></td>
                    </tr>
                    
                    
                     
                     <tr>
                         <td><?= /* noEscape */ __('Coupon Valid From'); ?></td>
                         <td><p>
                        <?= /* noEscape */ date('g:ia \o\n l jS F Y', strtotime($product->getEventStartDate())); ?>
                         </p></td>
                     </tr>
                     <tr>
                         <td><?= /* noEscape */ __('Coupon Expired On'); ?></td>
                         <td><p>
                        <?= /* noEscape */ date('g:ia \o\n l jS F Y', strtotime($product->getEventEndDate())); ?>
                         </p></td>
                     </tr>
                </table>
             </div>
        </div>
            <?php }
} else {
    echo '<h3 style="color:red">'.__('invalid Request').'</h3>';
}
?>