<?php
/**
 *
 * @category : FME
 * @Package  : FME_CheckoutOrderAttributesFields
 * @Author   : FME Extensions <support@fmeextensions.com>
 * @copyright Copyright 2018 © fmeextensions.com All right reserved
 * @license https://fmeextensions.com/LICENSE.txt
 */
/** @var $block \FME\CheckoutOrderAttributesFields\Block\Element\Date */
?>
<?php
$selectedOrder = $block->getSelectedOrder();
$selectedValues = $block->getValue();
if ($selectedOrder != null) {
    $coaf = json_decode($selectedOrder->getCoaf(), true);
    $selectedValues = isset($coaf[$block->getCurrentAttribute()->getAttributeCode()]['value'])?$coaf[$block->getCurrentAttribute()->getAttributeCode()]['value']:'';
}
$ElementClass = 'admin__field field date field-' . $block->getAttributeId();
$ElementClass .= $block->isRequired() ? ' required' : '';
?>
<div class="<?php /* @escapeNotVerified */ echo $ElementClass; ?>">
    <label class="label admin__field-label" for="<?php echo $block->getAttributeId()?>">
    	<span><?php /* @escapeNotVerified */ echo $block->getLabel() ?></span>
    </label>
    <div class="admin__field-control customer-dob">
        <?php echo $block->getDateElementHtml("customer_form", $selectedValues); ?>
        <?php if ($_tooltip = $block->getTooltip()) : ?>
        <div class="note"><?php /* @escapeNotVerified */ echo $_tooltip; ?></div>
        <?php endif; ?>
    </div>
</div>
