<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_SellerStorePickup
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

$_helper = $this->helper('Webkul\Marketplace\Helper\Data');
$dataHelper = $this->helper('Webkul\MarketplaceEventManager\Helper\Data');
$isPartner= $_helper->isSeller();
$magentoCurrentUrl = $block->getCurrentUrl();
$allow_pro_type=$_helper->getAllowedProductType();
$isSellerGroup = $_helper->isSellerGroupModuleInstalled();
if ($dataHelper->isEventManagerEnable()) {
    ?>
<style type="text/css">
    @media only screen and (max-width: 767px){

        .block-collapsible-nav.wk-mp-main{
            top: 20px;
        }
    }
</style>
        <nav class="account-nav">
            <ul class="nav items">
                <?php
                if ($isPartner) { ?>
                    <?php if (($isSellerGroup && $_helper->isAllowedAction('marketplaceeventmanager/event/add')) || !$isSellerGroup) { ?>
                    <li class="nav item <?= /* noEscape */ strpos($magentoCurrentUrl, 'marketplaceeventmanager/event/add')? "current":"";?>">      
                            <a href="<?= /* noEscape */ $block->getUrl('marketplaceeventmanager/event/add', ['_secure' => $this->getRequest()->isSecure()]); ?>">
                                <?php /* @escapeNotVerified */ echo __('Add Coupon Ticket') ?>
                            </a>                                     
                    </li>
                    <?php } ?>
                    <?php if (($isSellerGroup && $_helper->isAllowedAction('marketplaceeventmanager/event/eventlist')) || !$isSellerGroup) { ?>
                    <li class="nav item <?= /* noEscape */ strpos($magentoCurrentUrl, 'marketplaceeventmanager/event/eventlist')? "current":"";?>">      
                            <a href="<?= /* noEscape */ $block->getUrl('marketplaceeventmanager/event/eventlist', ['_secure' => $this->getRequest()->isSecure()]); ?>">
                                <?php /* @escapeNotVerified */ echo __('My Coupons List') ?>
                            </a>                                     
                    </li>
                    <?php } ?>
                <?php } ?>
            </ul>
        </nav>
<?php } ?>
