<!--
/**
 *
 * @category : FME
 * @Package  : FME_CheckoutOrderAttributesFields
 * @Author   : FME Extensions <support@fmeextensions.com>
 * @copyright Copyright 2018 © fmeextensions.com All right reserved
 * @license https://fmeextensions.com/LICENSE.txt
 */
-->
<?php
    $helper = $this->helper('FME\CheckoutOrderAttributesFields\Helper\Data');
    $order = $block->getOrder();
    if($order):
    $_coaf = $order->getCoaf();
    $coafFields = json_decode($_coaf,true);
?>
    <?php if ($_coaf != '' && !empty($coafFields)): ?>
	<div class="block block-order-details-comments">
	    <div class="block-title"><strong><?php /* @escapeNotVerified */ echo $helper->getHeading() ?></strong></div>
	    <div class="block-content">
		<table class="admin__table-secondary order-account-information-table">
		    <?php $i = 1; foreach ($coafFields as $field):
			if(isset($field['value']) && isset($field['email']) && $field['email'] == 1):
		    ?>
			<?php if($i%2 != 0): ?>
			    <tr>
			<?php endif;
				$val = is_array($field['value'])?implode(', ',$field['value']): $block->escapeHtml($field['value']);
                if (isset($field['type']) && $field['type'] == 'file') {
                    $val = "<a href='".$helper->getMediaUrl($field['value'])."'>".$field['value']."</a>";
                } elseif (isset($field['type']) && $field['type'] == 'image') {
                    $val = "<a href='".$helper->getMediaUrl($field['value'])."'><img src='".$helper->getMediaUrl($field['value'])."' alt='".$field['value']."' width='150px' /></a>";
                }
                ?>
                <td><?php /* @escapeNotVerified */ echo isset($field['label'])?$field['label']:''; ?></td>
                <td><?php  echo $val; ?></td>
			<?php if ($i == count($coafFields) && $i%2 != 0): ?>
			    <td>&nbsp;</td><td>&nbsp;</td>
			<?php elseif ($i%2 == 0 || $i == count($coafFields)): ?>
			    </tr>
			<?php endif; $i++; ?>
			<?php endif; ?>
		    <?php endforeach; ?>
		</table>
	    </div>
	</div>
    <?php endif; ?>
<?php endif; ?>
