<?php $captcha = $block->getCaptcha(); ?>
<?php if ($captcha->isEnabled()) : ?>
    <script type="text/javascript">
        require(['jquery'], function ($) {
            window.formToProtectOnPage = [];
            var currentFormId = '';
            reCaptchaFormsToProtect = <?php echo $captcha->getSelectorsJson() ?>;
            reCaptchaFormsToProtect.forEach(function (item) {
                formToProtect = $(item)[0];
                if (formToProtect) {
                    window.formToProtectOnPage.push(formToProtect);
                }
            });

            if (window.formToProtectOnPage.length) {
                var reCaptcha = document.createElement('script');
                reCaptcha.src = 'https://www.google.com/recaptcha/api.js?onload=invisibleCaptchaOnloadCallback&render=<?php echo $captcha->getSiteKey(); ?>';
                reCaptcha.attributes = 'async defer';
                document.body.appendChild(reCaptcha);
            }

            window.invisibleCaptchaOnloadCallback = function () {
                for (var i = 0; i < window.formToProtectOnPage.length; i++) {
                    var form = window.formToProtectOnPage[i];
                    jQuery('<input>').attr({
                        type: 'hidden',
                        class:'invisible_token',
                        name: 'invisible_token'
                    }).appendTo(form);
                }
                for (var i = 0; i < window.formToProtectOnPage.length; i++) {
                    var form = window.formToProtectOnPage[i];
                    if (form.tagName.toLowerCase() != 'form') {
                        continue;
                    }
                    currentFormId = form.id;
                    currentFormId = currentFormId.replace(/\W+(?!$)/g, '');
                    grecaptcha.ready(function() {
                        grecaptcha.execute('<?php echo $captcha->getSiteKey(); ?>', {action: currentFormId})
                            .then(function(token) {
                                jQuery('.invisible_token').val(token);
                            });
                    });
                }
            };
        });
    </script>
<?php endif; ?>



