<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /* @var $block \Magento\Catalog\Block\Product\View\AbstractView */?>
<?php $_product = $block->getProduct();
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
$storeManager  = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$storecode       = $storeManager->getStore()->getCode();
?>

<?php if ($block->displayProductStockStatus()) :?>
    <?php if ($_product->isAvailable() && $_product->getData('timerenabled') && (!is_null($_product->getSpecialPrice()))) :?>
            <div class="stock available" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
            <span><?= $block->escapeHtml(__('In stock')) ?>In Stock</span>
            </div>
    <?php endif; ?>
        <?php if ($_product->isAvailable() && !$_product->getData('timerenabled') && (is_null($_product->getSpecialPrice()))) :?>
            <div class="stock available" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
            </div>
       <?php if($storecode == 'ar'){?>
        <style type="text/css">
            .catalog-product-view .box-tocart{
                display: none;
            }
            .catalog-product-view .product.media::before
            {
                content: "";
                width: 250px; height: 250px;
                background: url("https://9yda.com/media/wysiwyg/deal_arabic.png") left top no-repeat;
                position: absolute;
                z-index: 3;
            }
        </style>
        <?php } else {?>
          <style type="text/css">
            .catalog-product-view .box-tocart{
                display: none;
            }
            .catalog-product-view .product.media::before
            {
                content: "";
                width: 250px; height: 250px;
                background: url("https://9yda.com/media/wysiwyg/deal_eng.png") left top no-repeat;
                position: absolute;
                z-index: 3;
            }
        </style>
        <?php } ?>
        <?php endif; ?>
        <?php if (!$_product->isAvailable()) :?>
        <div class="stock unavailable" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
        </div>
        <?php if($storecode == 'ar'){?>
        <style type="text/css">
            .catalog-product-view .product.media::before
            {
                content: "";
                width: 250px; height: 250px;
                background: url("https://9yda.com/media/wysiwyg/sold_arabic.png") left top no-repeat;
                position: absolute;
                z-index: 3;
            }
        </style>
                <?php } else {?>
                      <style type="text/css">
            .catalog-product-view .product.media::before
            {
                content: "";
                width: 250px; height: 250px;
                background: url("https://9yda.com/media/wysiwyg/sold_eng.png") left top no-repeat;
                position: absolute;
                z-index: 3;
            }
        </style>
        <?php } ?>
    <?php endif; ?>

<?php endif; ?>

