<?php
use Magento\Framework\App\Action\Action;
?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$isModuleEnable = $this->helper(\Sparsh\BuyNow\Helper\Data::class)->getConfig('buynow/general/enable_buynow');
$hideCart = $this->helper(Sparsh\BuyNow\Helper\Data::class)->getConfig('buynow/advance/hide_add_to_cart');
$magentoVersion = $this->helper(\Sparsh\BuyNow\Helper\Data::class)->getMagentoVersion();
$flag = 1;
if ($isModuleEnable):
    if (version_compare($magentoVersion, '2.3.0', '<') && !$hideCart): ?>
        <script type="text/x-magento-init">
        {
            "*": {
                "Sparsh_BuyNow/js/buy-now-button": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper(\Magento\Catalog\Helper\Output::class);
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?= /* @noEscape */ __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?= /* @noEscape */ ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info" data-container="product-<?= /* @noEscape */  $viewMode ?>">
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?= /* @noEscape */  $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                        <?= $productImage->toHtml() ?>
                    </a>
                    <div class="product details product-item-details">
                        <?php
                        $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?= /* @noEscape */ $_product->getProductUrl() ?>">
                                <?= /* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                            </a>
                        </strong>
                        <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                        <?= /* @noEscape */ $block->getProductPrice($_product) ?>
                        <?= $block->getProductDetailsHtml($_product) ?>

                        <div class="product-item-inner">
                            <div class="product actions product-item-actions"<?= /* @noEscape */ strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                <div class="actions-primary"<?= /* @noEscape */ strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form"
                                              data-product-sku="<?= /* @noEscape */ $block->escapeHtml($_product->getSku()) ?>"
                                              action="<?= /* @noEscape */ $this->helper('Magento\Catalog\Helper\Product\Compare')->getAddToCartUrl($_product) ?>"
                                              id="product_addtocart_form_<?= /* @noEscape */ $postParams['data']['product']; ?>"
                                              method="post">
                                            <input type="hidden" name="product" value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                                            <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <?php if ($isModuleEnable ? ($hideCart ? $flag = 0 : $flag) : $flag): ?>
                                                <button type="submit"
                                                        title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                        class="action tocart primary<?= /* @noEscape */ $isModuleEnable ? ' sparsh-buynow-custom-tocart' : '' ?>"
                                                >
                                                    <span><?= /* @noEscape */ __('Add to Cart') ?></span>
                                                </button>
                                            <?php endif; ?>
                                            <?php if ($isModuleEnable):
                                                $buttonTitle = $this->helper("Sparsh\BuyNow\Helper\Data")->getConfig('buynow/advance/button_title');?>
                                                <button type="submit"
                                                        title="<?= /* @noEscape */ $block->escapeHtml(__($buttonTitle)); ?>"
                                                        class="action primary sparsh-buynow-button"
                                                        data-mage-init='
                                                        {
                                                            "Sparsh_BuyNow/js/buy-now": {
                                                                "form": "#product_addtocart_form_<?= /* @noEscape */ $postParams['data']['product']; ?>"
                                                            }
                                                        }'
                                                >
                                                    <span><?= /* @noEscape */ __($buttonTitle) ?></span>
                                                </button>
                                            <?php endif; ?>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->isAvailable()): ?>
                                            <div class="stock available"><span><?= /* @noEscape */ __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?= /* @noEscape */ __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <div data-role="add-to-links" class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $position : '' ?>>
                                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                        <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <?php if ($showDescription):?>
                                <div class="product description product-item-description">
                                    <?= /* @noEscape */ $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?= /* @noEscape */ $_product->getProductUrl() ?>" title="<?= /* @noEscape */ $_productNameStripped ?>"
                                       class="action more"><?= /* @noEscape */ __('Learn More') ?></a>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
                <?= ($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()): ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @noEscape */ $_product->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>

