<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block \Magento\Customer\Block\Account\Forgotpassword
 */

/** @var \Magento\Customer\Block\Account\Forgotpassword $block */
?>
<?php
$randValue=substr(rand(),0,2);

$randValue1=substr(rand(),0,2);

$sum = $randValue.'+'.$randValue1;
?>
<form class="form password forget"
      action="<?= $block->escapeUrl($block->getUrl('*/*/forgotpasswordpost')) ?>"
      method="post"
      id="form-validate"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
        <div class="field note"><?= $block->escapeHtml(__('Please enter your email address below to receive a password reset link.')) ?></div>
        <div class="field email required">
            <label for="email_address" class="label"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input type="email" name="email" alt="email" id="email_address" class="input-text" value="<?= $block->escapeHtmlAttr($block->getEmailValue()) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">
            </div>
        </div>
        <?= $block->getChildHtml('form_additional_info') ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary captcha-validate"><span><?= $block->escapeHtml(__('Reset My Password')) ?></span></button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?= $block->escapeUrl($block->getLoginUrl()) ?>"><span><?= $block->escapeHtml(__('Go back')) ?></span></a>
        </div>
    </div>
</form>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$imagePath = $objectManager->get('Magento\Store\Model\StoreManagerInterface')->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);

?>
<style type="text/css" media="screen">

@import url('https://fonts.googleapis.com/css?family=Fredericka+the+Great');
.custom-captcha {
    width: 230px !important;
    height: 60px !important;
    text-align: center;
    font-size: 30px !important;
    background-image: url("<?php echo $imagePath."/captcha-bg.jpg"; ?>") !important;
    border: 1px solid #c2c2c2 !important;
    margin-bottom: 10px !important;
    margin-right: 15px;
    font-family: 'Fredericka the Great', cursive !important;
    border-radius: 3px !important;
    letter-spacing: 4.5px;
    margin-top: 10px;
}
.match-captcha label {
    margin-bottom: 10px;
}
.match-captcha label{
    width: 100%;
    text-align: left;
    margin-bottom: 0px !important;
}
.error-msg {
    color: #e02b27;
    margin-top: 7px;
}
input#check-value {
    margin-top: 7px;
}
</style>
<script>
require([
  'jquery',
  'mage/mage',
], function($){
   $( ".captcha-validate" ).click(function() {
       $('input').validation();
       if(!$('input[name="check"]').validation('isValid')){
            jQuery("#error").css("display" , "none");
        }
       if(!$('input').validation('isValid')){
           return false;
       } else if(jQuery("#value-sum").val() && jQuery("#check-value").val()) {
            if(!$('input[name="check"]').validation('isValid')){
               return true;
            }
            if(jQuery("#value-sum").val()!=jQuery("#check-value").val()){
                jQuery("#error").css("display" , "block");
                jQuery("#check-value").css("border-color" , "#ed8380");
                jQuery("#error").text("Incorrect CAPTCHA!")
                return false;
            }
            else{
                jQuery("#error").css("display" , "none");
                jQuery("#check-value").css("border-color" , "#cccccc");
            }
       } else {
            return true;
       }
   });
});
</script>
<script type="text/javascript">
captcha();
function captcha() {
    document.getElementById("check-value").value = "";
    var x = document.getElementById("randValue");
    var y = document.getElementById("randValue1");
    var concate = document.getElementById("rand-concate");
    var sum = document.getElementById("value-sum");
    x.value = Math.floor((Math.random() * 10));
    y.value = Math.floor((Math.random() * 10));
    concate.value = x.value + '+' + y.value;
    sum.value = parseInt(x.value) + parseInt(y.value);
}
</script>
